name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - master # Adjust to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Adjust to your Laravel PHP version
          extensions: mbstring, bcmath
          tools: composer

      # Step 3: Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Step 4: Upload to cPanel via FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp # Use `sftp` if needed
          local-dir: ./ # Directory of Laravel project on GitHub
          server-dir: /public_html/ # Adjust to the target directory in cPanel
