name: Laravel Deployment

on:
  push:
    branches: [master]  # Adjust to your deployment branch if different

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Clear Cache
        run: php artisan cache:clear
      - name: Clear Config
        run: php artisan config:clear
      - name: Clear Route
        run: php artisan route:cache
      - name: Generate Key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute Tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile Assets for Production
        run: npm run production

  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to cPanel via FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.demoboscosoft.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps  # Use FTPS for secure transfer
          local-dir: ./  # Adjust to your project root
          server-dir: /public_html/claret-eucharistic/  # Your target directory
          dry-run: false  # Set to true for testing before actual deployment
          exclude: |
            vendor/**  # Exclude vendor directory
            node_modules/**  # Exclude node_modules directory
            .env  # Exclude the .env file for security
            # Add any other files you want to exclude from deployment
